
def distribution(filename):
    file = open(filename, "r")
    content = file.read().split()
    a = content.count("A")
    aminus = content.count("A-")
    bplus = content.count("B+")
    b = content.count("B")
    bminus = content.count("B-")
    cplus = content.count("C+")
    c = content.count("B")
    cminus = content.count("B-")
    dplus = content.count("D+")
    d = content.count("D")
    dminus = content.count("D-")

    print(a, "students got A")
    print(aminus, "students got A-")
    print(bplus, "students got B+")
    print(b, "students got B")
    print(bminus, "students got B-")
    print(cplus, "students got c+")
    print(c, "students got C")
    print(cminus, "students got C-")
    print(dplus, "students got D+")
    print(d, "students got D")
    print(dminus, "students got D-")

distribution("dis.txt")